[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"

[build.processing]
  skip_processing = false

[build.processing.html]
  pretty_urls = true

# Explicitly serve the English index page
[[redirects]]
  from = "/en"
  to = "/en/"
  status = 301
  force = true

[[redirects]]
  from = "/en/"
  to = "/en/index.html"
  status = 200
  force = true

# Explicitly serve the subpaths under /en/
[[redirects]]
  from = "/en/*"
  to = "/en/:splat/index.html"
  status = 200

# Regular redirects for other paths
[[redirects]]
  from = "/success"
  to = "/success/"
  status = 301

[[redirects]]
  from = "/test-form"
  to = "/test-form.html"
  status = 200

[[redirects]]
  from = "/test-contact"
  to = "/test-contact.html"
  status = 200

[[redirects]]
  from = "/test"
  to = "/test/"
  status = 301

# This catch-all should be last
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Add cache control headers to prevent excessive caching
[[headers]]
  for = "/*"
    [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Cache-Control = "public, max-age=0, must-revalidate"

# Add specific headers for language paths
[[headers]]
  for = "/en/*"
    [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
    Pragma = "no-cache"
    Expires = "0"

# Explicitly declare the forms
[[forms]]
  name = "contact-form"
  
  [forms.fields]
    name = { required = true }
    email = { required = true }
    message = { required = true }

[[forms]]
  name = "test-form"
  
  [forms.fields]
    name = { required = true }
    email = { required = true }
    message = { required = true }

[[forms]]
  name = "minimal-test"
  
  [forms.fields]
    name = { required = true }
    email = { required = true }
    message = { required = true }