[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/success"
  to = "/success/"
  status = 301

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
    [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"

# Explicitly declare the form
[[forms]]
  name = "contact-form"
  
  [forms.fields]
    name = { required = true }
    email = { required = true }
    message = { required = true }
    bot-field = { required = false }