[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"

[build.processing]
  skip_processing = false

[build.processing.html]
  pretty_urls = true

# Simple redirects for specific URLs
[[redirects]]
  from = "/success"
  to = "/success/"
  status = 301

# Make sure the contact-form is accessible
[[redirects]]
  from = "/contact-form"
  to = "/contact-form.html"
  status = 200

# IMPORTANT: Allow Netlify to handle form submissions before the SPA redirect
[[redirects]]
  from = "/"
  to = "/.netlify/functions/submission-created"
  status = 200
  force = true
  conditions = {Content-Type = ["application/x-www-form-urlencoded"]}

# Standard SPA redirect
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
    [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"

# Keep only the contact form definition
[[forms]]
  name = "contact-form"
  
  [forms.fields]
    name = { required = true }
    email = { required = true }
    message = { required = true }