[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"

[build.processing]
  skip_processing = false

[build.processing.html]
  pretty_urls = true

[[redirects]]
  from = "/success"
  to = "/success/"
  status = 301

[[redirects]]
  from = "/test-form"
  to = "/test-form.html"
  status = 200

[[redirects]]
  from = "/test-contact"
  to = "/test-contact.html"
  status = 200

[[redirects]]
  from = "/test"
  to = "/test/"
  status = 301

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
    [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"

# Explicitly declare the forms
[[forms]]
  name = "contact-form"
  
  [forms.fields]
    name = { required = true }
    email = { required = true }
    message = { required = true }

[[forms]]
  name = "test-form"
  
  [forms.fields]
    name = { required = true }
    email = { required = true }
    message = { required = true }

[[forms]]
  name = "minimal-test"
  
  [forms.fields]
    name = { required = true }
    email = { required = true }
    message = { required = true }