[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/en"
  to = "/en/index.html"
  status = 200

[[headers]]
  for = "/*"
    [headers.values]
    Link = "</en>; rel=preload"